In [1]:
import pickle
import pandas as pd

with open("titanic_step4_importance_train.pickle", "rb") as pickle_filename :
    train_importance = pickle.load(pickle_filename)
with open("titanic_step4_importance_test.pickle", "rb") as pickle_filename :
    test_importance = pickle.load(pickle_filename)
with open("titanic_step4_importance_train_y.pickle", "rb") as pickle_filename :
    train_answer = pickle.load(pickle_filename)

In [2]:
train_importance.head()

,Initial_0,Pclass_2,Sex_0,Sex_1,HighChance_0,Cabin_0,Fare_0,LowChance_0,Ticket_Num_Cut_2,Family_2,...,Ticket_Num_Cut_3,Family_4,Family_0,Age_6,Fare_3,Cabin_4,Ticket_Initial2_2,Cabin_1,Age_1,Ticket_Initial2_15
0,1,1,1,0,1,1,1,1,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,1,0,0,...,1,0,0,0,1,0,0,1,0,0
2,0,1,0,1,1,1,1,1,0,0,...,0,0,1,0,0,0,1,0,0,0
3,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,1,1,1,0,1,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [3]:
test_importance.head()

,Initial_0,Pclass_2,Sex_0,Sex_1,HighChance_0,Cabin_0,Fare_0,LowChance_0,Ticket_Num_Cut_2,Family_2,...,Ticket_Num_Cut_3,Family_4,Family_0,Age_6,Fare_3,Cabin_4,Ticket_Initial2_2,Cabin_1,Age_1,Ticket_Initial2_15
0,1,1,1,0,1,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,1,0,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,1,1,1,0,0,0,...,0,0,1,1,0,0,0,0,0,0
3,1,1,1,0,1,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,1,0,1,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [4]:
train_answer.head()

   Survived
0       0.0
1       1.0
2       1.0
3       1.0
4       0.0

In [5]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy import stats

from sklearn.neighbors import KNeighborsClassifier        # 1. KNN 
from sklearn.linear_model import LogisticRegression       # 2. Logistic Regression
from sklearn.svm import SVC                               # 3. SVC
from sklearn.tree import DecisionTreeClassifier           # 4. Decision Tree
from sklearn.ensemble import RandomForestClassifier       # 5. Random Forest
from sklearn.ensemble import ExtraTreesClassifier         # 6. Extra Tree
from sklearn.ensemble import GradientBoostingClassifier   # 7. GBM
from sklearn.naive_bayes import GaussianNB                # 8. GausianNB
from xgboost import XGBClassifier                         # 9. XGBoost
from lightgbm import LGBMClassifier                       # 10. LightGBM

In [ ]:
logreg_model = LogisticRegression(C=846, penalty="12", random_state=1)