무신사 인기 브랜드가 실제 인스타에서도 인기가 있는지 인스타 크롤링으로 확인해보기

In [5]:
#MISSION 
#https://www.tiobe.com/tiobe-index/ 에서 1-10위까지 언어명만 크롤링

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time

URL = "https://www.tiobe.com/tiobe-index/"

service = Service(ChromeDriverManager().install())
options= Options()

# options.add_argument("--headless")
# options.add_argument("--disable-gpu")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-snadbox")

driver= webdriver.Chrome(service=service, options=options)
driver.get(URL)
time.sleep(3)

element = driver.find_elements(By.XPATH, "//table[contains(@id,'top20')]/tbody")

time.sleep(5)
for lang in element :
    k = lang.find_element(By.XPATH,"//tr//td[5]").text
    
    print(k[:10]) 
time.sleep(2)
driver.quit()

Python

In [ ]:
#pseudo-code -단계마다 print 해서 맞게 하고 있는지 확인하기
#무신사 사이트 접속

#상단 검색바 클릭

#인기 검색어 1위 키워드 서칭

#니트

#니트 키워드 입력> 니트 상품 PLP

#니트 관련 상품 목룍 > 인기 상품 5개만 선정

#인기상품 5개 각각의 상세페이지(PDP) 접속

#각 상품별 리뷰(댓글) 목록 확인

#해당 리뷰 수집

#엑셀 저장

#MySQL

In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time

URL = "https://www.musinsa.com/main/musinsa/"

service = Service(ChromeDriverManager().install())
options= Options()

# options.add_argument("--headless")
# options.add_argument("--disable-gpu")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-snadbox")

driver= webdriver.Chrome(service=service, options=options)
driver.get(URL)
time.sleep(3)

#상단 검색바 클릭
search_button = driver.find_element(By.CLASS_NAME, "Searchbar__TextFieldWrap-sc-dzagxs-2")
search_button.click()
time.sleep(5)



#인기 검색어 1위 키워드 서칭 -니트
popular_keyword = driver.find_element(By.CLASS_NAME, "search-home-popular-wrap")
items = popular_keyword.find_elements(By.TAG_NAME, "li")
target_keyword = items[0].text
time.sleep(3)


#니트 키워드 입력> 니트 상품 PLP
search_input = driver.find_element(By.CLASS_NAME, "search-home-search-bar-keyword")
search_input.clear()
search_input.send_keys(target_keyword)
search_input.send_keys(Keys.RETURN)
time.sleep(2)

print("타겟 키워드:", target_keyword )
print("페이지 타이틀:", driver.title )



driver.quit()

타겟 키워드: 후드집업
페이지 타이틀: 후드집업 | 무신사 추천 상품

In [5]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time
import re

URL = "https://www.musinsa.com/main/musinsa/recommend?gf=A"

service = Service(ChromeDriverManager().install())
options = Options()

# options.add_argument("--headless")
# options.add_argument("--disable-gpu")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-sandbox")

driver = webdriver.Chrome(service=service, options=options)
driver.get(URL)
time.sleep(2)

search_button = driver.find_element(By.CLASS_NAME, "Searchbar__TextFieldWrap-sc-dzagxs-2")
search_button.click()
time.sleep(2)

popular_keywords = driver.find_element(By.CLASS_NAME, "search-home-popular-wrap")
items = popular_keywords.find_elements(By.TAG_NAME, "li")
target_keyword = items[0].text
time.sleep(2)

search_input = driver.find_element(By.CLASS_NAME, "search-home-search-bar-keyword")
search_input.clear()
search_input.send_keys(target_keyword)
search_input.send_keys(Keys.RETURN)
time.sleep(2)

product_data = list()

for _ in range(6) :
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)

    products = driver.find_elements(By.CSS_SELECTOR, "div.sc-gSifMm.hWcAiF")[:15]

    for product in products :
        try :
            thumbnail_img = product.find_element(By.CSS_SELECTOR, 'div[data-mds="Image"] img')
            thumbnail_url = thumbnail_img.get_attribute("src")
            product_info = product.find_element(By.CSS_SELECTOR, "div.sc-hdBJTi.HekfN")
            brand = product_info.find_element(By.CSS_SELECTOR, "span.sc-dFVmKS.sc-kCuUfV.caMYFJ.fLhMxZ").text.strip()
            name = product_info.find_element(By.CSS_SELECTOR, "span.sc-dFVmKS.sc-dNdcvo.caMYFJ.coaQNK").text.strip()
            url = product_info.find_element(By.CSS_SELECTOR, "a.gtm-select-item").get_attribute("href")
            
            review_infos = product.find_elements(By.CSS_SELECTOR, r"span.text-\[11px\].leading-\[14px\].text-yellow.font-global")           
            rating_text = review_infos[0].text.strip() if len(review_infos) > 0 else ""
            review_rating = float(rating_text) if rating_text else 0
            
            review_count_before = review_infos[1].text.strip() if len(review_infos) > 1 else ""
            review_count_str = re.sub(r"[^\d]", "", review_count_before)
            review_count = int(review_count_str) if review_count_str else 0

            # --- 할인률 / 판매가 ---
            try:
                price_box = product.find_element(By.CSS_SELECTOR, "div.sc-kcLKEh.sc-dntSTA.khlneC.bhsCSX")
                spans = price_box.find_elements(By.CSS_SELECTOR, "span[data-mds='Typography']")
                texts = [sp.text.strip() for sp in spans if sp.text.strip()]
            
                discount_rate = texts[0] if len(texts) >= 2 else ""
                sale_price    = texts[1] if len(texts) >= 2 else (texts[0] if len(texts) == 1 else "")
            except:
                discount_rate = ""
                sale_price = ""


            product_data.append({"브랜드명" : brand, "상품명": name, "썸네일": thumbnail_url, "할인률": discount_rate, "판매가": sale_price, "URL": url, "평점": review_rating, "리뷰수": review_count})
        except Exception as e :
            print("데이터 크롤링 실패 :", e)
            continue

df = pd.DataFrame(product_data)
df_top10 = df.sort_values(by="리뷰수", ascending=False).head(10).reset_index(drop=True)

driver.quit()
df_top10

,브랜드명,상품명,썸네일,할인률,판매가,URL,평점,리뷰수
0,나이스고스트클럽,3STAR LOGO ZIP HOODIE_6colors(NG2EFUM480A),https://image.msscdn.net/thumbnails/images/goo...,35%,"64,350원",https://www.musinsa.com/products/4324664,4.8,972
1,에이지오디,2_WAY 스웨트 후디드 집업 [블랙],https://image.msscdn.net/thumbnails/images/goo...,58%,"18,760원",https://www.musinsa.com/products/3469896,4.7,849
2,더블유브이프로젝트,더스트 피그먼트 후드집업 다크그레이 MJOT7437,https://image.msscdn.net/thumbnails/images/goo...,36%,"49,800원",https://www.musinsa.com/products/1621921,4.7,845
3,일리고,129 로고 패치 후드 집업 블랙,https://image.msscdn.net/thumbnails/images/goo...,21%,"74,000원",https://www.musinsa.com/products/3651031,4.7,697
4,노르딕아일랜드,DW N로고 후드집업 - 네이비,https://image.msscdn.net/thumbnails/images/goo...,35%,"57,850원",https://www.musinsa.com/products/2285140,4.7,228
5,썬번프로젝트,"Logo Patch Hoodie Zip-up, PURPLE",https://image.msscdn.net/thumbnails/images/goo...,15%,"118,150원",https://www.musinsa.com/products/5333962,4.8,169
6,어반디타입,어반스텔라 스웻 후드 집업_5color,https://image.msscdn.net/thumbnails/images/goo...,52%,"37,990원",https://www.musinsa.com/products/5281249,4.9,158
7,이알티알,Ad Astra Appliqué 2way Hoodie Zip Up Grey,https://image.msscdn.net/thumbnails/images/goo...,31%,"89,000원",https://www.musinsa.com/products/4826665,4.8,130
8,오와이,PRAY HARD HOODIE ZIP UP - BLACK,https://image.msscdn.net/thumbnails/images/goo...,30%,"76,300원",https://www.musinsa.com/products/5345813,4.9,129
9,글랙,[글랙 × 지꾸] GZHD001 헤이즈 와플 집업 후드 (GREEN),https://image.msscdn.net/thumbnails/images/goo...,,"89,000원",https://www.musinsa.com/products/5390372,4.9,118

In [25]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time
import re

URL = "https://www.musinsa.com/main/musinsa/recommend?gf=A"

service = Service(ChromeDriverManager().install())
options = Options()

# options.add_argument("--headless")
# options.add_argument("--disable-gpu")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-sandbox")

driver = webdriver.Chrome(service=service, options=options)
driver.get(URL)
time.sleep(2)

search_button = driver.find_element(By.CLASS_NAME, "Searchbar__TextFieldWrap-sc-dzagxs-2")
search_button.click()
time.sleep(2)

popular_keywords = driver.find_element(By.CLASS_NAME, "search-home-popular-wrap")
items = popular_keywords.find_elements(By.TAG_NAME, "li")
target_keyword = items[0].text
time.sleep(2)

search_input = driver.find_element(By.CLASS_NAME, "search-home-search-bar-keyword")
search_input.clear()
search_input.send_keys(target_keyword)
search_input.send_keys(Keys.RETURN)
time.sleep(2)

product_data = list()

for _ in range(2) :
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)

    products = driver.find_elements(By.CSS_SELECTOR, "div.sc-gSifMm.hWcAiF")[:3]

    for product in products :
        try :
            thumbnail_img = product.find_element(By.CSS_SELECTOR, 'div[data-mds="Image"] img')
            thumbnail_url = thumbnail_img.get_attribute("src")
            product_info = product.find_element(By.CSS_SELECTOR, "div.sc-hdBJTi.HekfN")
            brand = product_info.find_element(By.CSS_SELECTOR, "span.sc-dFVmKS.sc-kCuUfV.caMYFJ.fLhMxZ").text.strip()
            name = product_info.find_element(By.CSS_SELECTOR, "span.sc-dFVmKS.sc-dNdcvo.caMYFJ.coaQNK").text.strip()
            url = product_info.find_element(By.CSS_SELECTOR, "a.gtm-select-item").get_attribute("href")
            
            review_infos = product.find_elements(By.CSS_SELECTOR, r"span.text-\[11px\].leading-\[14px\].text-yellow.font-global")           
            rating_text = review_infos[0].text.strip() if len(review_infos) > 0 else ""
            review_rating = float(rating_text) if rating_text else 0
            
            review_count_before = review_infos[1].text.strip() if len(review_infos) > 1 else ""
            review_count_str = re.sub(r"[^\d]", "", review_count_before)
            review_count = int(review_count_str) if review_count_str else 0

            # --- 할인률 / 판매가 ---
            try:
                price_box = product.find_element(By.CSS_SELECTOR, "div.sc-kcLKEh.sc-dntSTA.khlneC.bhsCSX")
                spans = price_box.find_elements(By.CSS_SELECTOR, "span[data-mds='Typography']")
                texts = [sp.text.strip() for sp in spans if sp.text.strip()]
            
                discount_rate = texts[0] if len(texts) >= 2 else ""
                sale_price    = texts[1] if len(texts) >= 2 else (texts[0] if len(texts) == 1 else "")
            except:
                discount_rate = ""
                sale_price = ""


            product_data.append({"브랜드명" : brand, "상품명": name, "썸네일": thumbnail_url, "할인률": discount_rate, "판매가": sale_price, "URL": url, "평점": review_rating, "리뷰수": review_count})
        except Exception as e :
            print("데이터 크롤링 실패 :", e)
            continue

df = pd.DataFrame(product_data)
df_top3 = df.sort_values(by="리뷰수", ascending=False).head(3).reset_index(drop=True)

driver.quit()
df_top3

,브랜드명,상품명,썸네일,할인률,판매가,URL,평점,리뷰수
0,제멋,헤븐 투웨이 테리 후드집업 8종 버건디 KJHD2523,https://image.msscdn.net/thumbnails/images/goo...,29%,"33,210원",https://www.musinsa.com/products/3551178,4.8,587
1,코드그라피,(우먼) 코튼 후드 집업_3color,https://image.msscdn.net/thumbnails/images/goo...,82%,"18,000원",https://www.musinsa.com/products/3837517,4.9,49
2,오운서,[블루클로젯 X 오운서] 마이 그래니 스티치 퍼 후드 집업 (퍼 탈부착 가능_2 C...,https://image.msscdn.net/thumbnails/images/goo...,40%,"82,800원",https://www.musinsa.com/products/5727484,4.9,17

In [ ]:
#인기상품 5개 각각의 상세페이지(PDP) 접속
#각 상품별 리뷰(댓글) 목록 확인
#해당 리뷰 수집
#엑셀 저장

In [31]:
from openpyxl import Workbook

driver= webdriver.Chrome(service=service, options=options)
all_reviews = list()

for idx, row in df_top10.iterrows() : #-> 한 행씩 값을 읽기를 반복하겠다는 매서드 함수
    print(f"{idx+ 1}번째 상품리뷰 수집 중 :", row["상품명"])  #-> 중간에 오류지점을 추적하기 위함
    driver.get(row["URL"])
    time.sleep(2)

    try : 
        review_tab = driver.find_element(By.CSS_SELECTOR,"button[data-button-id='prd_review_tab']")
        review_tab.click()
        time.sleep(2)

        review_elements = driver.find_elements(By.CSS_SELECTOR, "div.ExpandableContent__Container-sc-1951ro-0 > div.ExpandableContent__ContentContainer-sc-1951ro-1 span.text-body_13px_reg.w-full.text-black.font-pretendard")
        for review in review_elements :

            text = (review.text or "").strip()

            if not text : 
                continue
            
            all_reviews.append({
                "브랜드" : row["브랜드명"],
                "상품명" : row["상품명"],
                "URL": row["URL"],
                "리뷰수": row["리뷰수"],
                "리뷰" : review.text.strip(),
                "평점" : row["평점"]
            })
      
    except Exception as e :
        print("리뷰수집 실패 :", e)
        continue


driver.quit()

wb = Workbook()
ws = wb.active
ws.title = "무신사 리뷰"
ws.append(["브랜드","상품명","URL","리뷰수","리뷰","평점"])  #-> 행에 목록 추가: []

for item in all_reviews : 
    ws.append([item["브랜드"],item["상품명"],item["URL"],item["리뷰수"],item["리뷰"],item["평점"]])

file_name = "musinsa_top10_reviews.xlsx"
wb.save(file_name)

print("엑셀파일 저장완료:", file_name)

1번째 상품리뷰 수집 중 : 2Way 후드 패딩 아크틱 라이트웨이트 히트 점퍼
2번째 상품리뷰 수집 중 : Edelweiss Quilted Jacket Navy
3번째 상품리뷰 수집 중 : [시티 레저] 우먼즈 시어 립스탑 후디드 라이트 다운 재킷 [라이트 그레이]
4번째 상품리뷰 수집 중 : 후드 경량 다운 자켓_3colors
5번째 상품리뷰 수집 중 : BACK LOGO DUCK DOWN LIGHTWEIGHT PADDED JACKET -BLACK
6번째 상품리뷰 수집 중 : TCM mini logo raglan light puffer jacket (white)
7번째 상품리뷰 수집 중 : 슈퍼라이트 인슐레이션 점퍼 점퍼 챠콜
8번째 상품리뷰 수집 중 : 미니멀 경량 후디드 패딩 자켓 _Olive
9번째 상품리뷰 수집 중 : 7K72060 남성 모노 튜브 스텐넥 다운 자켓
10번째 상품리뷰 수집 중 : 아이언 라이트 다운 자켓 (5color)
엑셀파일 저장완료: musinsa_top10_reviews.xlsx

In [ ]:
#MySQL 저장하기

In [1]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\hjkim\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\hjkim\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hjkim\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import re
import hashlib
from sqlalchemy import create_engine, text

EXCEL_PATH = "musinsa_top10_reviews.xlsx"
HOST = "127.0.0.1"
PASSWORD = "Hayeon123!"
USER = "root"
PORT = 3306
DB = "musinsa_db" 

df = pd.read_excel(EXCEL_PATH)

ENGINE = create_engine(f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB}?charset=utf8mb4", pool_pre_ping= True, pool_recycle=3600)

df.columns = [str(c).strip() for c in df.columns] #리스트안에 담겨있음 [브랜드, 상품명, url, 리뷰수, 리뷰, 평점]
needed = ["브랜드","상품명", "URL", "리뷰수", "리뷰", "평점"]

missing = [c for c in needed if c not in df.columns]
#-> 6개의 필드명에 눈에 보이지 않는 화이트 스페이스가 존재할 수 있기 때문에 그 값을 각각 문자의 형태로 가져와서 다시 리스트를 만드는 전처리 진행.
#-> 

if missing : 
    raise ValueError(f"엑셀에서 해당 컬럼을 찾지 못했습니다 : {missing}")

def extract_product_id(url: str) -> int | None : #-> int로 반환하거나 or none
    if not url :
        return None
    m = re.search(r"/products/(\d+)", str(url))  #-> url에서 products뒤에 나오는 1개 이상의 정수를 찾아와라
    return int(m.group(1)) if m else None #-> 가장 처음 나오는 숫자그룹을 정수 형태로 가져와라

def sha1_text(s: str) ->str :
    s = (s or "").strip()
    return hashlib.sha1(s.encode("utf-8")).hexdigest()


    
out = pd.DataFrame()
#데이터 백만개중에 하나라도 값의 형태가 다르면 백만개 다 날라감.따라서 꼼꼼하게 형변환 체크 및 통일시키기
out["brand"] = df["브랜드"].astype(str).str.strip()  #->데이터를 str형태로 바꾸고. 그 해당 str을 찾아와서 strip한다
out["product_name"] = df["상품명"].astype(str).str.strip() 
out["url"] = df["URL"].astype(str).str.strip() 
out["product_id"] = out["url"].apply(extract_product_id)  #-> 해당 함수에 url 컬럼의 각각 값을 적용해라
out["review_count"] = df["리뷰수"]
out["rating"] = df["평점"]
out["review_text"] = (
    df["리뷰"].astype(str)
    .str.replace("\u200b", "", regex=False)  #- whitespace 값 없애기
    .str.replace("\xa0", " ", regex=False)    #- escape sequence 값을 여백 한개로 줄이기
    .str.replace(r"\s+", " ", regex=False)   #- 정규표현식으로 여러개 공백을 1개로 줄이기
    .str.strip()
)
out["review_hash"] = out["review_text"].apply(sha1_text) #-> 중복되는 review값은 같은 코드를 가져서 중복값인지
out["source_file"] = EXCEL_PATH

out = out[out["review_text"].notna() & (out["review_text"] != "")]
out = out.drop_duplicates(subset=["review_hash"]) #-> hash를 기준으로 중복값은 제거해라

# MySQL에 보내기  -> SQL문법으로 써야함

INSERT_SQL = text("""
INSERT INTO musinsa_reviews 
(brand, product_name, product_id, url, review_count, rating, review_text, review_hash, source_file)
VALUES
(:brand, :product_name, :product_id, :url, :review_count, :rating, :review_text, :review_hash, :source_file)
ON DUPLICATE KEY UPDATE
    rating = VALUES(rating),
    review_count = VALUES(review_count),
    product_name = VALUES(product_name),
    brand = VALUES(brand),
    url = VALUES(url),
    source_file = VALUES(source_file);
""")

def chunked(iterable, size: int) :     #-> 데이터가 너무 대량이면 오래걸리니까 덩어리씩 분할해서 보내자
    for i in range(0, len(iterable), size) :
        yield iterable[i:i+size]

#list 형태인 out을 행을 기준으로 하는 딕셔너리 형태로 바꾸기
records = out.to_dict(orient="records")
CHUNK_SIZE = 2000

with ENGINE.begin() as conn :
    for batch in chunked(records, CHUNK_SIZE) :
        conn.execute(INSERT_SQL, batch)

print(f"완료: {len(records)}건 처리완료")

완료: 89건 처리완료

# 인스타 크롤링
그동안의 크롤링은 로그인 과정 불필요 => 선택자만 잘 정의한다면 크롤링 문제 X

로그인이 필요한 모든 사이트:
-> 최초에 한번만 로그인 과정을 진행 후 2번째부터는 굳이 로그인 요구 X 하게 만들기

로그인:

In [ ]:
# 밑에 진행하기 위해 인스타 로그인 id,pw 미리 메모 후 40초 이내에 기입
#틀리면 끝장남

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time
import re
import pickle

URL = "https://www.instagram.com/accounts/login/"  

service = Service(ChromeDriverManager().install())
options = Options()

# options.add_argument("--headless")
# options.add_argument("--disable-gpu")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-sandbox")

driver = webdriver.Chrome(service=service, options=options)
driver.get(URL)

print("수동으로 로그인 후 40초 안에 인증을 완료해주세요")
time.sleep(40)
#40초 안에 로그인해야함

#로그인 이후 쿠키값 탈취해서 저장해
with open("instagram_cookies.pkl","wb") as f :
    pickle.dump(driver.get_cookies(), f)


print("쿠키저장완료")


driver.quit()

수동으로 로그인 후 40초 안에 인증을 완료해주세요
쿠키저장완료

In [26]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from urllib.parse import quote, urlparse
import re
import time
import pickle

URL = "https://www.instagram.com/"

service = Service(ChromeDriverManager().install())
options = Options()

# options.add_argument("--headless")
# options.add_argument("--disable-gpu")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-sandbox")

driver = webdriver.Chrome(service=service, options=options)
driver.get(URL)

# Refactoring을 위한 유틸리티 함수
def wait_post_loaded(driver, timeout) :
    wait = WebDriverWait(driver, timeout)
    wait.until(EC.presence_of_element_located((By.TAG_NAME, "main")))
    wait.until(lambda d: len(d.find_elements(By.XPATH, "//main//a[@href]")) > 0)

def find_scroll_container_in_main(driver) :
    main = driver.find_element(By.TAG_NAME, "main")
    canditates = main.find_elements(By.XPATH, ".//*[contains(@class, 'x78zum5') or contains(@style, 'overflow')]")

    best = None
    best_h = 0

    for el in canditates :
        try :
            h = driver.execute_script("return arguments[0].clientHeight;", el)
            sh = driver.execute_script("return arguments[0].scrollHeight;", el)

            if sh > h and h > best_h :
                best = el
                best_h = h
        except :
            pass

    return best

def scroll_inside(driver, el, max_round, pause) :
    last = -1
    for _ in range(max_round) :
        driver.execute_script("arguments[0].scrollTop = arguments[0].scrollHeight;", el)
        time.sleep(pause)
        cur = driver.execute_script("return arguments[0].scrollTop;", el)
        if cur == last :
            break
        last = cur

def extract_username_from_href(href) :
    if not href:
        return None

    path = urlparse(href).path.strip("/")

    if not path :
        return None

    if path.startswith(("p/", "reel/", "tv/", "explore/", "accounts/")) :
        return None

    username = path.split("/")[0]

    if re.fullmatch(r"[A-Za-z0-9._]{1,30}", username) :
        return username

    return None

    # url = "https://www.instagram.com/musinsa.official/path=/utm=""/"
    # parsed = urlparse(url)
    # parsed = {"scheme":"https", "netloc":"www.instagram.com", "path":"/musinsa.official/"}

def get_author_id(driver) :
    main = driver.find_element(By.TAG_NAME, "main")
    anchors = main.find_elements(By.XPATH, ".//a[@href]")

    best = None
    best_y = 10**9

    for a in anchors :
        href = a.get_attribute("href") or ""
        username = extract_username_from_href(href)

        if not username :
            continue

        txt = (a.text or "").strip()
        if txt.startswith("@") :
            continue

        try:
            y = a.location["y"]
            if y < best_y :
                best_y = y
                best = username
        except :
            pass
            
    return best 

def get_comments(driver) :
    main = driver.find_element(By.TAG_NAME, "main")
    spans = main.find_elements(By.XPATH, ".//span[@dir='auto' and not(ancestor::*[@role='button'])]")

    comments = []
    
    for s in spans :
        t = s.text.strip()

        if not t :
            continue

        if re.fullmatch(r"\s*\d+\s*(주|일|시간|분|초)", t) :
            continue

        if len(t) <= 1 :
            continue

        comments.append(t)

    seen = set()
    uniq = list()
    
    for c in comments :
        if c not in seen :
            seen.add(c)
            uniq.append(c)
    return uniq

        # 정규표현식 : 특정한 형태의 패턴을 가지고 있는 문자열을 찾아내고 싶을 때 사용!
        # (주|일|시간|분|초) : | => vertical bar => or
        # \s* : * => 0개 또는 그 이상 => 아무것도 존재하지 않을수도 있고, 복수의 값이 있을 수도 있다
        # \s : 여백, 공백 등의 white space
        # 10 주 10주
        # \d+ : + => 1개 이상이 존재, \d => decimal => 정수
        # 10주
        # 엔터     엔터
        # 똑같은 댓글 -> 같은댓글
    
with open("instagram_cookies.pkl", "rb") as f :
    cookies = pickle.load(f)

for cookie in cookies :
    driver.add_cookie(cookie)

driver.refresh()
time.sleep(10)

try :
    btn = driver.find_element(By.XPATH, "//button[normalize-space()='나중에 하기' or normalize-space()='정보 저장']")
    btn.click()
    time.sleep(2)
except :
    pass

print("정상적인 로그인 후 나중에 하기 버튼 클릭 완료")

base_url = "https://www.instagram.com"
results = list()

brands = (
    df_top3["브랜드명"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
    .tolist()
)

print("브랜드 수: ", len(brands))

for keyword in brands :
    encoded = quote(keyword)
    tag_url = f"{base_url}/explore/tags/{encoded}"
    driver.get(tag_url)
    time.sleep(5)

    post_link = set()

    for _ in range(2) :
        links = driver.find_elements(By.TAG_NAME, "a")
        for link in links :
            href = link.get_attribute("href")
            if href and "/p/" in href :
                if href.startswith("/p/") :
                    href = base_url + href
                post_link.add(href)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(3)

    print(f"[{keyword}] 수집된 게시물 수 :", len(post_link))

    for url in list(post_link) :
        driver.get(url)

        try :
            wait_post_loaded(driver, timeout=15)
            
        except Exception as e :
            print(f"페이지 로딩 실패:, {keyword} | {url} | {e}")
            results.append({"brand": keyword, "url": url, "author_id": None, "comments": []})
            continue

        try :
            scroll_box = find_scroll_container_in_main(driver)
            if scroll_box :
                scroll_inside(driver, scroll_box, max_round=10, pause=1)
        except :
            pass

        try :
            author_id = get_author_id(driver)
            comments = get_comments(driver)
        except Exception as e :
            print(f"추출 실패: {keyword} | {url} | {e}")
            author_id, comments = None, []

        results.append({
            "brand": keyword,
            "url": url,
            "author_id": author_id,
            "comments": comments
        })

for r in results[:20] :
    print(r["brand"], r["url"])
    print("author:", r["author_id"])
    print("comments:", r["comments"])
    print("=" * 60)
    
driver.quit()

print("총 결과 수: ", len(results))

정상적인 로그인 후 나중에 하기 버튼 클릭 완료
브랜드 수:  3
[제멋] 수집된 게시물 수 : 28
[코드그라피] 수집된 게시물 수 : 26
[오운서] 수집된 게시물 수 : 15
제멋 https://www.instagram.com/p/DUDK3T8D3Gy/
author: ears.vintage
comments: ['ears.vintage', 'ears.vintage\n 3주\n#ears구매가능 \n\n🏆\n품명 : 제멋 ma-1\n사이즈 : XL (총기장69 / 가슴단면71)\n가격 : 20000\n\n🚥\n상품에 관련된 모든 문의는 DM 주세요\n중고의 특성상 사용감 존재할 수 있습니다\n부담없는 가격에 데일리하게 착용가능합니다\n다량구매시에 적당선 네고 해드립니다 👍', '댓글을 남겨보세요.', '1월 28일']
============================================================
제멋 https://www.instagram.com/p/CFHN53zHCK7/
author: jemut_shop
comments: ['jemut_shop', 'jemut_shop\n 284주\n슬슬 MA-1 자켓을 준비해야할때!\n제멋 인기 제품인 [리치 오버 MA-1 자켓] vs [노블 투웨이 오버핏 MA-1 자켓]\n본격 파헤쳐서 비교해봤습니다 >..<\n( 곧 신상도 나옵니다🥺💜 )\n_\n#제멋 #jemut\n#노블투웨이오버핏MA-1자켓 #리치오버MA-1자켓 #오버핏MA-1자켓 #MA-1자켓 #항공점퍼 #항공자켓 #오버핏항공자켓 #박새로이코디 #박새로이항공점퍼 #박새로이룩 #박새로이옷', '댓글을 남겨보세요.', '2020년 9월 14일']
============================================================
제멋 https://www.instagram.com/p/CM4DqNXnmDB/
author: hiphoper_com
comments: ['hiphoper_com', "hiphoper_com\n 256주\n⠀\n지갑 걱정? 해 줄 필요 없는🙅\u200d♂️\n가성비 코디 스타일링🙆\u200d♂️\n⠀\n🍪힙합퍼 스낵칩🍪\n스낵 콘텐츠의 'Snack'과\n코디의 'C' 힙합퍼의 'HIP'\nHIPHOPER Snack CHIP😎🎉\n⠀\n씹을수록 재미있는 코디 스낵칩🥨\n언제든 스낵칩을 꺼내먹어요🍫\n⠀\n⠀\nmon.\n아우터 #제멋 집업자켓\n이너 제멋 티셔츠\n바지 제멋 생지 데님\n신발 #다온아토 독일군러너\n가방 #플레이언 미니백\n⠀\ntue.\n셔츠 #페플 포켓셔츠\n이너 제멋\n바지 #퍼스텝 데님\n신발 #캐치볼\n⠀\nwed.\n셔츠 #제멋 더블포켓셔츠\n이너 제멋\n바지 제멋 밴딩팬츠\n신발 #야세 더비\n안경 #세미콜론아이웨어\n⠀\nthu.\n상의 #더블유브이프로젝트 후드\n이너 제멋\n바지 더블유브이프로젝트 와이드팬츠\n신발 캐치볼\n가방 #이스트팩 숄더백\n⠀\nfri.\n상의 페플 후드\n이너 제멋\n바지 제멋 밴딩 팬츠\n신발 #엑셀시오르\n가방 #믈링\n⠀\n#힙합퍼 #hiphoper", 'sklfashiondxb', 'Nice 🔥🔥🔥🔥', '_daong_2', '@exmkunk 올 ,,', 'awhloeseel', '@_c._.hyun 이거 종민이 스탈이구만 ?', 'hollaween.5', 'Promote on @migosrecords', 'hondaione', '🙌😍🙌', '2021년 3월 26일']
============================================================
제멋 https://www.instagram.com/p/C0I_w5evsw6/
author: jemut_shop
comments: ['jemut_shop', 'jemut_shop\n 수정됨\n•\n117주\n🔥제멋 베스트 후드 추가 컬러🔥\n- ARK ROLLING OVERFIT NAPPING HOOD\n제멋 인기 그래픽 후드인 아크 롤링 오버핏 기모 후드!!\n트렌디한 브라운과 버건디 컬러가 패키지와 함께 추가되었습니다~👏👏\n\n#jemut #제멋 #23fw #신상컬러', '2023년 11월 27일']
============================================================
제멋 https://www.instagram.com/p/CV7AGi8pwl_/
author: seoulstore_official
comments: ['seoulstore_official', 'seoulstore_official\n 224주\n𝐁𝐑𝐀𝐍𝐃 𝐃𝐀𝐘 l 더블유브이프로젝트, 제멋 𝐮𝐩 𝐭𝐨 𝟑𝟓%\n\n베이직한 디자인이 가득한 더블유브이프로젝트, 제멋 단독 할인 진행 중! 자주 손이 가는 아이템을 찾았다면? ☝스토리 링크 클릭하고 구경해보세요\n\n#더블유브이프로젝트 #제멋 #데일리템\n#후드집업추천 #맨투맨추천 #니트추천', '댓글을 남겨보세요.', '2021년 11월 6일']
============================================================
제멋 https://www.instagram.com/p/C6lKJrCPGxa/
author: zzangmen_77
comments: ['zzangmen_77', '베트남 나트랑', 'zzangmen_77\n 94주\n🇻🇳OOTD', 'ulim_h', '더운 날에도 멋찐 사럄 🔥❤️', '🇻🇳', '2024년 5월 5일']
============================================================
제멋 https://www.instagram.com/p/C2EJn2dvlv6/
author: 4910_official
comments: ['4910_official', 'DLanger•Whatever Helps Remix (Sleeping Lion) (Instrumental)', '4910_official\n 110주\n인기 후드티 맛집 모음🙌\n어떤 스타일의 후드티가 가장 마음에 드시나요?😁\n\n👉더 많은 상품은 4910에서 확인해 주세요!\n\n❇️ 지금 4910앱을 설치하고 다양한 혜택을 누려보세요!\n📦4910은 하나만 사도 365일 무료배송', '2024년 1월 14일']
============================================================
제멋 https://www.instagram.com/p/B5kVSpVg8m0/
author: nail_ato
comments: ['nail_ato', 'nail_ato\n 325주\n👉🏻👉🏻👉🏻\n#화이트그라데이션네일 은 역시 겨울에해야 제멋^_^‼️‼️\n❤️\n❤️\n❤️\n👉현금결제시 모든시술회원가적용🙆\n.\n.\n🌸가격및예약문의\n☎01073246630\n✔카톡아이디  nailato2017\n⭐️ @nail_ato\n.\n.\n\n#네일아토#인싸#인스타뷰티#시청역네일#시청역네일샵#시청역속눈썹연장#남대문네일샵#남대문네일 #회현역네일#회현역속눈썹연장#젤네일#속눈썹연장#셀피#셀스타그램#글리터네일#daily #fff#ネイル#풀스톤네일#화려한네일#유행네일#스톤네일#네일#그라데이션브러쉬 네일#겨울네일#💅🏼', '댓글을 남겨보세요.', '2019년 12월 2일']
============================================================
제멋 https://www.instagram.com/p/CmwXMBvqeyD/
author: bs_oo_s
comments: ['bs_oo_s', '협찬 광고\nEric Godlow•Peace', 'bs_oo_s\n 수정됨\n•\n164주\n#협찬 \n\n@6ft_official 에서 첼시부츠를 협찬받았습니다.\n\n다양한 착장과 다양한 무드로 코디하기 좋은 첼시부츠네요.\n\n깔끔한 라인감과 사이드라인에 신축성 밴딩이 개인적으로 너무 마음에 들었어요!!👍\n\n저는 제주도에 잘 도착했습니다✈️\n제주 협찬촬영도 기대해주세요😎\n\n협찬해주신 @6ft_official 감사합니다.\n\n#식스핏 #SIXFT #부츠 #부츠추천 #제멋 #신발추천 #데일리슈즈 #첼시부츠추천 #남자슈즈추천 #데일리룩 #일상룩 #ootd #리뷰메이커 #오늘의코디 #코디추천 #패션코디 #인플루언서 #selfie #daily #dailylook #ulzzang #korean #전신샷 #reels #reelsinstagram #reelsinsta #협찬문의 #협찬환영', 'connecte__', '압코 쉐입 넘 예뿌자나여,,,🙉✨️', 'yoom_niverse', '와 나도 첼시부츠 협찬 . . .대박적 당신 짱 능력자!', 'meyou_0117', '코디랑 완전 딱이다..👍🏻👍🏻 캐리어까지 체고..', 'coma_comma_jason', '오우,, 첼시부츠 넘나 이뻐버리네요?😍👍✨🔥🔥🔥 제주 촬영 빨리 보여주세요 현기증 난단 말이에요🙀✨🔥🔥🔥', '1___sol___', '제주 이쁜곳들 너무 가득해요', 'bubble_gum_s2', '첼시부츠 진재 너무 이쁘자나요🥹 저는 어제 제주도에서 집으로 왔네옹!/@!', 'heee__.j', '아니 넘 이쁜 첼시부츤데요..! 제주 넘 부러워요 ㅜ', 'god_good_god_good', '첼시부츠 섹시함 그 자체네요😮 팬츠 색감이랑도 너무 잘 맞네요!🔥', 'secregar_', '제주도 부럽씁니다....피드 기대하면 되는건가용🫢🫢', 'chunparkk', '완전 딱이라구요! 저도 갖고싶덩🖤', 'yedungg', '첼시부츠랑 떡코랑 넘나 잘 어울리네용 😮 핏감 최고시당 ..', '9.hyxn', '첼시부츠 고급지네유!!!🔥🙌', 'w0_n__', '제주 사진들 기대하고 있겠습니담!!', 'joo_jamjam', '첼시 부츠 너무 예쁜데요??! 캬 🔥🔥', 'b_sh1ny', '여행 부러워용❤️', '2022년 12월 29일']
============================================================
제멋 https://www.instagram.com/p/C_2I63xv3B6/
author: all.the.vintage
comments: ['all.the.vintage', '베니스 스퀘어', 'all.the.vintage\n 75주\n[올더빈티지]\n\n제품명:제멋 웨스턴 투턱 와이드 팬츠\n사이즈:30\n\n구매문의는\nDM부탁드립니다.\n\n빈티지제품 특성상 얼룩외 세월의흔적 있을 수 있습니다.\n컨디션 고려하며 한장한장 초이스하니 \n이점 참고 부탁드립니다 :)\n\n시흥시 서울대학로278번길 61 베니스스퀘어\n1층 C동 4호', '댓글을 남겨보세요.', '2024년 9월 13일']
============================================================
제멋 https://www.instagram.com/p/BKtegcEgagJ/
author: mmmh_linda
comments: ['mmmh_linda', '샹제리제거리', 'mmmh_linda\n 수정됨\n•\n176주\n#paris #파리 #나비투어🌎 \n이렇게 더운 빠리라니. . .\n차가운 바람이길 바랐는데 아쉽다.\n빠리는 겨울이 제멋💋\n#LindaXParis', 'chichj77', '간만에 댓글 남겨요^^포스팅은 늘 잘 보고 있구요. 발렌티노 슈즈 잘 어울리세요👠', 'shinymomhouse', '서울도 오늘은 덥네요^^ 감기조심요~~~~', 'eb1810', '@mihyang_seo 비오고 비바람불고 장난이 아니었지요 날씨 좋은 파리 여행 즐겁게 하세요😉', '@meenjukim 어머 파리에 계시는 거에요? 반갑네요. 한번 쯤 살아보고 싶다 생각하는 도시인데 계신다니 부럽습니다❤️', '@jinhwatae 진짜 너무 걸었더니 먹어도 살이 빠져요. 밀가루 탓인지 두드러기 올라오고 난리에요 지금 ㅜ ㅋ ㅋ', '@nobel1220 이젠 나이 드니까 힐은 버겁네요 ㅜ', '@myeongk__ 아니에요. 기온차 크다는데 감기 조심하셔요❤️', '@yumi.yun.1 하하하 빠리가 열일했지요😅', '@duckyeon_k 그쵸 그쵸. 뽜리는 그 맛이죠. 그러다 뜨끈한 우동 한 사발👍', '@hyun_ss 고맙습니다😁😁', '@sweetmj84 제가 아니라 빠리기 그렇잖아요😅😅😅', '@oh_hwajung 진짜 스니커즈 땀이 차네요😂😂', '@cottageofamerind 그쵸? 코트 잔뜩 챙겼는데 아무데서도 못 입네요 ㅜ', '@eb1810 며칠 전까지 추웠나 봐요.비가 안 오니 그냥 좋네요😅', 'merci_mlle_ju', '나비님을 파리 블로그 게시물로 통해 알게되었는데 나비님덕분에 인스타도 시작했는데 같은 파리하늘 아래라니요ㅠㅠ괜히 막 혼자 반갑고그래요🙆🙆 지나가다마주치면소리지를꺼같아요💕꺅ㅋㅋㅋㅋㅋㅋㅋㅋㅋ', '2016년 9월 24일']
============================================================
제멋 https://www.instagram.com/p/CYI5XfYlmCq/
author: maebulshow
comments: ['maebulshow', "maebulshow\n 수정됨\n•\n216주\n❤안녕하세요, 매불쇼 가족 여러분! 쫄짜 PD입니다❤\n연말에 따뜻한 소식을 하나 전해드리려고 합니다🎁\n\n지난번 품-절 사태를 일으킨 '매불쇼X제멋브랜드' 의류 판매로 생긴 기부금을 드디어 전달했습니다👏👏👏👏\n\n✔기부는 유난히 추운 올 겨울에 따뜻한 연탄이 필요한 가정들을 위해 '(사)따뜻한 한반도 사랑의 연탄나눔운동'이라는 단체에 기부했습니다.\n\n✔여러분들의 따뜻한 마음이 모여 생긴 기부금은 1,500만원! 연탄으로는 18,000장이 올 겨울 연탄이 필요한 가정에 지원이 될 예정입니다.\n\n항상 매불쇼 사랑해주시는 가족 여러분 한 해 동안 매불쇼 사랑해주셔서 감사했습니다. 내년에는 더욱더 재밌는 매불쇼로 찾아뵙겠습니다❤\n\n#매불쇼 #정영진 #최욱 #제멋", 'artcare_yoon', '👏👏👏', 'ssenchunge', '속보이는 기부쇼 하지 말고 K리그 비판 범죄 조장 사과 안하실건가요? 나중에 꼭 벌 받으실겁니다…', '6een2', '욱이형 2만장 된거지..? 리스펫', 'kyoungho_kang', '❤️매불짱 최욱 역쉬 통큰 사나이~~~~^^', 'ahnnnjh1202', '피디님 유지은씨 이다슬씨 좀 불러주세요', 'super_mang9', '코로나 끝나고 다음연말에는 매불쑈 콘서트 갑시다아!!👏', 'calice1004', '👏👏👏 즐거움과 감동을 동시에 주시네요', 'anbongdu', '욱이형 영진이형 최고', 'gem980', '두 분 건강하게 오래 방송해 주세요.', 'toureve.pmj', '새해에도 재밋는 방송 부탁드립니다 ^^', 'seojeongja968', '우기 니가 최고당', 'coolguy991', '최욱 연탄2000장 추가 기부 굿!!!!!', 'pgh3633', '이만 장 채운 갓욱 멋진 남자.', 'sean_s._do', '역시 최욱 멋있는 최욱 응원할게요 👏🔥❤️', 'maesil_joj_jang', '기부는 언제나 올다❤️❤️❤️', '2021년 12월 31일']
============================================================
제멋 https://www.instagram.com/p/CApT55VpHNZ/
author: crewbi_official
comments: ['crewbi_official', 'crewbi_official\n 300주\n🎈지금 크루비에선? 제멋 브랜드 세일 중!🎈\n세일기간 임박!🛵 서두르세요!\n⠀ ⠀⠀\n#크루비 #CREWBI #제멋', '댓글을 남겨보세요.', '2020년 5월 26일']
============================================================
제멋 https://www.instagram.com/p/B3L89XCJf3c/
author: m_up_healee_
comments: ['m_up_healee_', 'm_up_healee_\n 333주\nJEMUT 제멋 F/W Season [Essential Wear]💛 Hair Make up by @m_up_healee_\n\n#jemut #streetfashion #lookbook', '댓글을 남겨보세요.', '2019년 10월 4일']
============================================================
제멋 https://www.instagram.com/p/CCsxOJZJssD/
author: an__dante_
comments: ['an__dante_', '서울', 'an__dante_\n 수정됨\n•\n289주\n그대가 자꾸 생각나요\n-\nKeep thinking about you\n-\nTop: @lab101_official \nBottom: @jemut_shop \nShoes: @excelsior_official \n-\n#협찬 #일상 #서울 #제멋 #엑셀시오르 #랩101 #jemut #excelsior #lab101 #daily #ootd #seoul #한여름의추억', 'sara.mangone', 'Watch "tune in for love" and let me know if you liked it 🌹', 'shimochi_', 'this pic is so cool omg', 'yong.jun_2', '무드 너무 이뻐요🤗', 'frannzees', '💕💓', 'nancyfiorii', 'i love you', 'mascianicholas_', 'sungkil.hong', '😁😄👏👍', 'ale.stubbs', 'Are you emotionally connecting with the wall? A new ship is born 👏', 'cher31_', '“Act natural “ 😂', 'iconicmoonjuice', "It's comfortable?🦄", 'giuliatomasiii', 'Luv u 🥺💙', 'crown__ye', '나는?', 'ph__sso', '감성지는구먼요😆', '2020년 7월 16일']
============================================================
제멋 https://www.instagram.com/p/DPOK0bPk4fX/
author: 1o._.z3
comments: ['1o._.z3', '서울', '1o._.z3\n 21주\n제멋 피팅 촬영때!!\n\n#fyp#Selfie#reels#freelancermodel#daily#서울#촬영#좋아요#배우#배우프로필#배우지망생#오디션#신인배우모집#배우오디션#방송연예과#숏폼#신인배우#모델#광고모델#협찬#프리랜서모델#동덕여대방송연예과#freelancer#model#화장품모델#피팅모델#광고#모델프로필#웨딩모델#뷰티모델', '_ruby_kr', '증말 예쁘시다', '___yeonxs', '아름답다...', 'daye_ev', '귀여웡 땅콩같아🥜', 's_eulkii', '_c2heee', '예뿌다 .. 옘버 ..', 'ol_somang', '빛나요', 'wozxenl_', '❤️', 'pxrxming', '아기여워', 'yoong_zii', '가을여신 조희주', '_m0n0___', '마지막 비니 픽입니다', '2025년 9월 30일']
============================================================
제멋 https://www.instagram.com/p/C9o_ikwP8o9/
author: myvideodiary_kr
comments: ['myvideodiary_kr', 'Sabrina Carpenter•Espresso', 'myvideodiary_kr\n 수정됨\n•\n83주\nDaily look 48.\n.\n.\n오늘도 블랭크룸을 입어봤습니다. 확실히 이쁜 제품들은\n손에 자주 가는거 같아요. 오늘은 캐주얼하게 입어봤는데요.\n카고팬츠와 스트라이프로 여름에도 캐주얼하게 연출해보았습니다.\n\n오늘은 집안에서 데일리룩을 찍어본김에\n어색했던 미소도 장착해서 찍어봤는데요.\n아무래도 입은 올라가있는데 눈은 안 웃으니까 이상한거 같아요 ㅋㅋㅋ 아직 연습이 더 필요할듯..\n\n평소에 미소를 안 짓는건 아니지만 웃는 모습의 릴스를 보시는 분들도 웃으실 수 있도록 저도 웃어볼게요\n(언제까지 할지는 모르겠지만..)\n\nOuter : \nTop : 블랭크룸\nInner : \nPants : 제멋\nShoes : 반스\n\n#여름코디 #휴가코디 #쉬운코디 #카고팬츠룩 #카고팬츠코디', 'kwn0sxng', '표정이 한결 좋아보이시능걸용🔥🔥', 'fitting170cm', 'ㅋㅋ오늘 넘 귀여우신데용?! 마지막 뛰는거 킬포!!😍', 'pocketrateye', '저연스러운 표정이 참 어려운거같아요😭', 'ju_1_1ook', '오 반팔티 컬러가 너무 좋네요😁', 'gong2_hjin', '마무리 완전 큐트하십니당💙', 'lysseong_', '안녕하세요 패션 맞팔하고 소통 같이해요😍❤️', 'oh_taexy', '스트라이프 티셔츠 좋네유!!🙌🙌', 'thinkgyu_about', '캐주얼하고 톤온톤 느낌이라 편안하고 이쁜 코디네요💙💙', 'duning_d', '잔잔한 스트라이프 사룽인걸요💙', '159.ootd', '스트라이프 경쾌해보여서 조은데여?! 컬러도 조쿠요! 웃으니깐 훨씬 보기 조아용🙌', 'congmannn', '은은한 색감 좋아요🙌', 'ootd.wannieee___', '잔스트라이프는 역시 꾸러기미 넘치는 아이템인것 같아요💙 넘 잘어울리시는!', 'thmxv', '피드를 사랑하십시오❤️❤️', 'aidme21', '엇 릴스영상이 몬가 더 자연스러워진것같아여🔥🔥🔥', 'jun_beommmmmmm', '오 티셔츠아주맛잇네용😍', '2024년 7월 20일']
============================================================
제멋 https://www.instagram.com/p/DT17dYXiZBU/
author: hyek_408
comments: ['hyek_408', 'hyek_408\n 4주\n강아지 옆에 고양이 옆에 강아지 🐶🐱\n\n.\n@4910_official \n#협찬 #4910 #4910패션스태프\n\n[Outter] 제멋 : @jemut_shop \n“네트로 오버핏 후드 집업“\n그레이 / L\n\n🫶 4910 제멋에서 만날 수 있습니다.\n\n🫶 후드집업 하면 가장 중요한 건 모자인데, 이 제품은 모자 속이 깊고 두께도 있어서 맘에 드는 핏이 나와요!\n\n🫶 기모가 추가되어 보온성은 물론이고 입었을 때 포근한 느낌도 들어요! 요즘 같은 날 추운 겨울에 기모 없으면 감기 걸리기 딱 좋거든요… 🥺\n\n🫶 어느 컬러나 무난하게 어울리는 그레이 컬러 제품이라서 안에 원색 받혀서 입으면 자연스럽게 너무 잘 어울리죠!', 'soo_lookbook', '강얼쥐와 냥이들 모두 너무 귀여운데요 ☺️ 후드집업만큼 편한 게 또 없죠 🙌🙌', 'hongga_ga', '무드 너무 이쁘네요 🙌', '0_black_ootd', '레드 포인트 좋네요!!', 'j.wj601', '후디 코디 꾸안꾸로 넘 좋네요!', 'pak.aspakas', '레드 레이어드 좋은데요 😍', 'ju_1_1ook', '캐주얼 무드 이쁘네요👏👏👏', 'koko.iron', '후디 휘뚤마뚤 좋은데요🔥🔥', 'leica_me_together', '무드 너무좋은데요😍', 'itsjuniq', '퀄리티좋네요👏👏', 'yony_ootd', '오오 제멋 아이템들 탄탄하다던데 ! 레드 포인트에 데님까지 레이어드 센스 넘 좋으시쟈나요 ~~🙊✨️🍫 게다가 뒤에 댕댕이들 잔뜩 넘 힐링 뽀쨕이.... 세상 기여워요,,,😆🐕', 'th2__a', '캐주얼🙌', 'younootd', '레드포인트 맛깔나네요 😍', 'v9v9v9ri8', '가디건 레이어드 진짜 좋당...크', 'easy.dailylook', '오옷!이 옷 진짜 따뜻해보이고 귀엽네요ㅎㅎ 강아지들이랑 고양이도 넘 사랑스럽고, 포근한 느낌이 딱 좋아요~ㅋㅋ', 'dhnuvy', '강아지 넘 귀욥,,❤️', '1월 23일']
============================================================
제멋 https://www.instagram.com/p/DBGpdHdpDdw/
author: inst__public
comments: ['inst__public', 'Connor Price, Killa•AMG', 'inst__public\n 71주\n쌈@뽕한 맨투맨 추천⠀ ⠀ ⠀⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ ⠀ ⠀ -⠀⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ ⠀ -⠀ ⠀⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ -⠀ ⠀ ⠀⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ ⠀ ⠀ ⠀⠀ ⠀ ⠀ #코디 #맨투맨 #비바라비다 #파르티멘토 #펜필드 #제멋 #언더오프 #코드그라피 #엠엠엘지 #아웃스탠딩 #헤더헬렌 #와이케이', '2024년 10월 14일']
============================================================
제멋 https://www.instagram.com/p/BuCMN9Wgspd/
author: of_the9
comments: ['of_the9', 'of_the9\n 366주\n_\n역시 트렌치코트는 박시해야 제멋 ✔️\n.\n.\n.\n.\n.\n.', 'custom_thehats', '단체모자제작 전문 마이캡입니다. 행복한 하루 되세요~', 'ysmg_cheongyangni', '오늘 즐거운 하루 되세용', 'jm.e4.ts', '매출증진에 고민이 있으시다고요? 저희 제이엠 마케팅 과 상담해보세요', 'with_chae.a', '크! 사진색감이 느무 이뻐요ꈍ◡ꈍ\n오직 ‘인스타’로만 매일 7O마논~\n제꺼에두 놀러와주쎄요오 💛', '#insta##daily#dailylook#데일리#데일리룩#ootd#outfit#오오티디#아웃핏#일상#오늘#옷가게#여자옷#대전옷가게#여자옷가게#대전#청주#천안#대전맛집#대전카페#봉명동#은행동#둔산동#매장#스토어팜#오브더나인', '2019년 2월 19일']
============================================================
총 결과 수:  69

#인스타그램 cookie 탈취 -> 자동로그인무신사를 통해 크롤링한 브랜드명을 가져다가 인스타그램 검색 -> 해당 검색된 브랜드 검색결과 창에서 2번의
#38개의 URL을 한번씩 방문하면서 아래와 같은 정보 다시 찾아오기
#브랜드명 & 게시글 작성자 & 게시글 댓글
#MySQL-> SQL문법을 활용해서 값을 분석
#인스타그램 내 페이지 이동하는 단계가 유독 시간이 많이 걸리는 지점 => timesleep 만으로는 안될때가 생김 -> 게시물의 인기나 정보량에 따라 너무 달라짐

=> 최대로 기다릴 수 있는 시간을 정해놓고, 만약 그 시간 이전에 데이터 값을 찾아오면 해당 값을 받아서 그 다음단계 바로 실행
=> 최대로 기다릴 수 있는 시간을 초과 -> 에러발생시키지말고 그 다음 컨텐츠로 넘어가

In [1]:
import pymysql

MYSQL_HOST = "127.0.0.1"
MYSQL_PORT = 3306
MYSQL_USER = "root"
MYSQL_PW = "Hayeon123!"
MYSQL_DB = "instagram_review01"
MYSQL_CHARSET = "utf8mb4"

rows = list()

for r in results :
    brand = r.get("brand")
    post_url = r.get("url")
    author_id = r.get("author_id")
    comment_text = r.get("comments")

    for c in comment_text :
        c = c.strip()
        rows.append((brand, post_url, author_id, c))

print("DB INSERT 대상 row 수:", len(rows))

conn = pymysql.connect(
    host=MYSQL_HOST,
    port=MYSQL_PORT,
    user=MYSQL_USER,
    password=MYSQL_PW,
    database=MYSQL_DB,
    charset=MYSQL_CHARSET
)

try : 
    with conn.cursor() as cur :
        sql="""
        INSERT INTO ig_tag_comments (brand, post_url, author_id, comment_text) 
        VALUES (%s, %s, %s,%s);
        """

        for row in rows : 
            cur.execute(sql, row)
    
    conn.commit()
    print("MySQL 저장완료!")
    
except Exception as e :
    conn.rollback()
    print("저장실패: ", e)

finally :
    conn.close()

NameError: name 'results' is not defined

오늘의 미션
selenium -> 11번가에서 "캠핑용품" 검색 후 출력되는 상품명 100개 크롤링하기

In [25]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time

URL = "https://www.11st.co.kr/"

service = Service(ChromeDriverManager().install())
options= Options()

# options.add_argument("--headless")
# options.add_argument("--disable-gpu")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-snadbox")

driver= webdriver.Chrome(service=service, options=options)
driver.get(URL)
time.sleep(3)

search_btn = driver.find_element(By.CSS_SELECTOR,"input.search_text")
search_btn.click()
time.sleep(2)

search_btn.send_keys("캠핑용품")
search_btn.send_keys(Keys.RETURN)
time.sleep(2)

items = driver.find_elements(By.CSS_SELECTOR, "div.search_content")

for item in items :
    title = item.find_elements(By.CSS_SELECTOR, "section.search_section ul > li div.c-card-item__name")                      
    print(title.text)

driver.quit()

AttributeError: 'list' object has no attribute 'text'