In [ ]:
# pandas -> 데이터 (1, 2차원 형태) -> 시각화 (plotly : express, graph objects)
# EDA
# 브라질(남미)에서 꽤 큰 이커머스 비즈니스 플랫폼 (olist) 의 실제 데이터를 기반으로 문제찾기, 시각화, EDA
# 데이터 프로젝트 참고

In [ ]:
# 1) 데이터 출처, 주제
# 데이터 사이즈
# 데이터 요소 특성 확인

In [ ]:
# 데이터가 어느 분야(산업)에서 나온 데이터인가!!!
# 의류, 식품, 주류, 홈쇼핑, 이커머스, IT, 가구, 화장품, 자동차....
# 그래서 첫 회사, 첫 사회진입 분야 중요 (분야, 산업계 -> 마케팅 직군)
# 도메인 학습

# 이커머스 => 학습
# 온라인 비즈니스의 한 종류 (고객이 온라인을 통해서 상품 조회. 구매. 결제 실행 -> 배송단계 -> 고객 상품 도달 -> 리뷰.평점 -> 재구매 발생)
# 데이터 사이언티스트, 데이터 분석가 => 채용공고 (새로운 업계, 분야를 즐겁게, 오픈마인드로 학습할 마인드, 자세)
# 온라인 비즈니스 타입
# B2C : Business To Customer (기업과 고객) : 쿠팡, SSG
# B2B : Business To Business (기업과 기업) : MRO, 폐쇄몰
# B2BC : Business To Business Customer (기업과 기업 & 고객) : BBQ, 아리따움
# D2C : Direct To Customer (기업이 직접 고객 데이터를 수집할 수 있는 비즈니스 모델)
# 특정 지역.국가 문화적 특징 : 함부로 머리를 자르지 않는다, 머리카락 귀하게 (영혼) -> 헤어케어
# 바디케어, 향수
# 우리나라 -> 빨리빨리 민족 -> 산업반영 -> 상품 구매 결정 -> 단계 최소
# 일본 -> 라쿠텐 (구매 -> 정말이요? -> 지역)
# 미국 -> 아마존 (구매 -> 쿠폰적용 -> 발급 -> 온라인, 오프라인 -> 지역매장)
# 브라질 -> olist (결제 단계, 카테고리별, 상품별 단계)


# olist : 비즈니스 중계 플랫폼 형태
# A라는 업체가 온라인으로 상품을 판매하고 싶어함 (직원, 마케팅, 등록, 배송, 물류 -> x)
# A <-> olist (계약)
# A -> olist (물류창고 상품 입고)
# A -> olist (상품 등록 메뉴얼 -> 상품등록)
# A의 상품, 주문 -> olist에서 주문확인 & 물류창고 입고 A상품 조회 -> 고객 배송
# A의 고객, 상품 수령 -> 이메일을 통해서 상품 주문.배송 관련 후기 작성 요청
# A의 고객, 후기 작성 & 등록
# A는 olist 계약당시, 서명한 정산날짜에 A의 고객이 입금한 결제금액, 수수료 제외하고 입금

In [1]:
# 신사업, 스타트업, 서비스 (NSM)
# 기존 사업 히스토리 기반, 더 좋은 서비스 (Problem Definition -> NSM)
# 위에서 산정한 목표에 도달하기 위해서 우리가 알아야하는 최소한의 정보?

In [ ]:
# 2) 데이터 사이즈 = 크기 확인

In [ ]:
# 3) 데이터 요소 속성 특징 확인 = 수치(변이, 위치), 범주(순서, 목록), 관계
# 수치형 : 5 numbers summary (평균, 표준편차, 분산, 최소, 최대, 사분위, 이상치 등)
# 시계열 데이터 차트 : 추이.트랜드
# boxplot, histogram, heatmap, scatter, line 차트

# 범주형 : 상대빈도, 절대빈도 (각각의 독립적인 데이터 수치)
# 세로, 가로 막대 그래프 차트
# 원형차트, 폭포차트, 리본차트

In [ ]:
# 현재 해당 서비스를 사용하고 있는 고객은 얼마나 있는가? -> 얼마나 많은 고객이 존재하는가?
# 고객은 주로 어디에서 거주하고 있는가?
# 고객은 주로 어떤 결제방법을 사용하고 있는가?
# 고객들의 평균 거래액은 얼마일까?
# 일별.주별.월별 판매 트랜드는 어떻게 되고있을까?
# 어떤 카테고리에서 많은 매출이 나오고 있는가? -> 어떤 카테고리를 더 성장시켜야 할까?

In [8]:
import pandas as pd

PATH = "00_data"

products = pd.read_csv(f"{PATH}/olist_products_dataset.csv", encoding="utf-8-sig")
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [3]:
products.shape

(32951, 9)

In [4]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [5]:
products.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [ ]:
# olist에 등록된 상품갯수는 32,951 // 결측정보 약 600여개 // 대부분 실수자료형 수치형 데이터

In [9]:
import pandas as pd

PATH = "00_data"

customers= pd.read_csv(f"{PATH}/olist_customers_dataset.csv", encoding="utf-8-sig")
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [10]:
customers.shape

(99441, 5)

In [11]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [ ]:
# 고객 정보데이터, 99,441개, 결측데이터 없음, 고객 정보데이터는 대부분 문자열 -> 범주형 데이터

In [12]:
customers.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [13]:
import pandas as pd

PATH = "00_data"

geolocation = pd.read_csv(f"{PATH}/olist_geolocation_dataset.csv", encoding="utf-8-sig")
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [14]:
geolocation.shape

(1000163, 5)

In [ ]:
# 약 100만개 정도의 위치정보 (주문 고객관련), 결측치 존재x, 정수, 실수, 문자열 형태 -> 다양한 타입

In [15]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [16]:
geolocation.describe() # e+ : exponent(지수) -> 지수표기법, 밑 & 지수

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

In [17]:
import pandas as pd

PATH = "00_data"

order_items = pd.read_csv(f"{PATH}/olist_order_items_dataset.csv", encoding="utf-8-sig")
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [18]:
order_items.shape

(112650, 7)

In [ ]:
# 상품 주문관련 데이터의 갯수는 11만개 정도, 결측 존재 x, 수치 데이터의 단위 = 브라질 헤알, 상품판매가 평균 120헤알, 중간값 74헤알, 향후 산점도 차트 -> 저가 & 가성비 상품이 많이 몰려 -> 고가의 프리미엄 상품이 산발적으로 흩어져있을 것이다

In [19]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [20]:
order_items.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [21]:
import pandas as pd

PATH = "00_data"

payments = pd.read_csv(f"{PATH}/olist_order_payments_dataset.csv", encoding="utf-8-sig")
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [22]:
payments.shape

(103886, 5)

In [ ]:
# 결제 수단 및 방법관련 데이터의 총 갯수는 약 10만건, 결제 단계 몇단계 구분 (sequential)